### ISSUE TITLE
No syntax highlighting for entities

### ISSUE THREAD

**Issue by gideongrinberg** [wasp-lang/vscode-wasp#1]
Essentially, it's what the title says. There is no syntax highlighting or Intellisense for entities.

<img width="594" alt="Screen Shot 2020-11-09 at 9 19 36 AM" src="https://user-images.githubusercontent.com/49839886/98552633-b4333800-226c-11eb-9ea3-c133369351f3.png">

**Comment by Martinsos** [comment]
@Gideon357 thanks for reporting this!

You are right, unfortunately we didn't get that working properly yet.
I actually left a comment for it in the code, I will reference it here: https://github.com/wasp-lang/vscode-wasp/blob/main/syntaxes/wasp.tmLanguage.yaml#L45 .

The thing is, we are using `prisma` language extension on the {=psl psl=} block as embedded language (feature of VSCode), but what we have in PSL block actually isn't complete PSL declaration of entity -> it is missing start `model Task {` and end `}` because we moved those parts out into Wasp (`entity Task`).

Some possible solutions:
- Implement our own highlighting of Prisma code, that takes into account that parts of model statement are missing. While this would work, we would be replicating logic that is already implement in Prisma VSCode extension, and probably works better.
- Drop PSL and implement our own Entity syntax -> then we implement syntax highlighting for it.

Plan is to go with latter at some moment, so for now it probably makes most sense to not put additional effort into it and then once we have our own Entity syntax, we will implement proper highlighting support for it.

I will leave the issue open in case somebody has better ideas how to approach this.

**Comment by infomiho** [comment]
No longer relevant since we using `schema.prisma` file now.
